local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set('', '<Leader>f', function()
    hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, { remap = true })
vim.keymap.set('', '<Leader>F', function()
    hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, { remap = true })
vim.keymap.set('', '<Leader>t', function()
    hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
end, { remap = true })
vim.keymap.set('', '<Leader>T', function()
    hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
end, { remap = true })
vim.keymap.set('', '<Leader>j', function()
    hop.hint_lines_skip_whitespace({direction = directions.AFTER_CURSOR, current_line_only = false})
end, { remap = true })
vim.keymap.set('', '<Leader>k', function()
    hop.hint_lines_skip_whitespace({direction = directions.BEFORE_CURSOR, current_line_only = false})
end, { remap = true })
